### ISSUE TITLE
Practica 3 Visual Studio UX UI

### ISSUE THREAD

**Issue by HECTOR-KDM02** [SistemasTecTlaxiaco/actividad-3-practica-de-interfaz-grafica-con-interactividad-team-ola#1]
[Practica 3 Visual Estudio.docx.pdf](https://github.com/SistemasTecTlaxiaco/actividad-3-practica-de-interfaz-grafica-con-interactividad-team-ola/files/14339218/Practica.3.Visual.Estudio.docx.pdf)

(REPORTE PRACTICA 3)

**Comment by josealfredo79** [comment]
Calificacion...???

**Comment by HECTOR-KDM02** [comment]
Calificacion 19%

**Comment by josealfredo79** [comment]
Bien hecho y revisado...

**Comment by Bryan080204** [comment]
Determinamos que la calificaion es:
19%

**Comment by Bryan080204** [comment]
calificacion 15%
